#!/usr/bin/env python3
"""Generate Ledge's deterministic documentation diagrams and terminal GIF.

Static SVGs use only the Python standard library. The animated terminal GIF
also needs Pillow. Use --capture-terminal to refresh terminal-demo.json from
a real release-build run before rendering the GIF.
"""

from __future__ import annotations

import argparse
import io
import json
import math
import re
import shlex
import subprocess
import sys
from pathlib import Path
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "docs" / "assets"
BOOK_ASSETS = ROOT / "docs" / "book" / "src" / "assets"
REPORT = ROOT / "benchmarks" / "results" / "2026-07-l1" / "summary.md"
TERMINAL_DATA = ASSETS / "terminal-demo.json"
GENERATED = "<!-- Generated by scripts/generate_demo_assets.py; do not edit by hand. -->"

SOLVER_COLORS = {
    "ledge": "#2563eb",
    "osqp (lifted)": "#f59e0b",
    "clarabel (lifted)": "#10b981",
}


def architecture_svg() -> str:
    return f"""<svg xmlns="http://www.w3.org/2000/svg" width="920" height="390" viewBox="0 0 920 390" role="img" aria-label="Ledge architecture overview">
  {GENERATED}
  <defs>
    <marker id="arrow" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z" fill="#64748b"/></marker>
  </defs>
  <rect width="920" height="390" rx="18" fill="#f8fafc" stroke="#cbd5e1"/>
  <text x="36" y="42" font-family="Georgia,serif" font-size="24" fill="#0f172a">One open core, two entry points</text>
  <text x="36" y="69" font-family="system-ui,sans-serif" font-size="14" fill="#475569">Portfolio semantics stay above the factor-structured numerical kernel</text>

  <rect x="38" y="104" width="190" height="92" rx="12" fill="#eff6ff" stroke="#3b82f6" stroke-width="2"/>
  <text x="133" y="137" text-anchor="middle" font-family="system-ui,sans-serif" font-size="17" font-weight="700" fill="#1d4ed8">Python / NumPy</text>
  <text x="133" y="164" text-anchor="middle" font-family="ui-monospace,monospace" font-size="13" fill="#1e40af">PortfolioProblem</text>
  <text x="133" y="184" text-anchor="middle" font-family="ui-monospace,monospace" font-size="13" fill="#1e40af">sequence · solve_batch</text>

  <rect x="38" y="226" width="190" height="92" rx="12" fill="#ecfdf5" stroke="#10b981" stroke-width="2"/>
  <text x="133" y="259" text-anchor="middle" font-family="system-ui,sans-serif" font-size="17" font-weight="700" fill="#047857">Rust API</text>
  <text x="133" y="286" text-anchor="middle" font-family="ui-monospace,monospace" font-size="13" fill="#065f46">ledge crate</text>
  <text x="133" y="306" text-anchor="middle" font-family="ui-monospace,monospace" font-size="13" fill="#065f46">problem · sequence · batch</text>

  <line x1="228" y1="150" x2="294" y2="192" stroke="#64748b" stroke-width="2" marker-end="url(#arrow)"/>
  <line x1="228" y1="272" x2="294" y2="230" stroke="#64748b" stroke-width="2" marker-end="url(#arrow)"/>

  <rect x="304" y="118" width="246" height="186" rx="14" fill="#f5f3ff" stroke="#8b5cf6" stroke-width="2"/>
  <text x="427" y="153" text-anchor="middle" font-family="system-ui,sans-serif" font-size="18" font-weight="700" fill="#6d28d9">Portfolio layer</text>
  <text x="427" y="184" text-anchor="middle" font-family="system-ui,sans-serif" font-size="13" fill="#5b21b6">budget · boxes · exposure templates</text>
  <text x="427" y="208" text-anchor="middle" font-family="system-ui,sans-serif" font-size="13" fill="#5b21b6">L1/L2 turnover · tracking error</text>
  <text x="427" y="232" text-anchor="middle" font-family="system-ui,sans-serif" font-size="13" fill="#5b21b6">workspace · warm-start sequence</text>
  <text x="427" y="256" text-anchor="middle" font-family="system-ui,sans-serif" font-size="13" fill="#5b21b6">serde replay · account batch</text>
  <rect x="346" y="272" width="162" height="23" rx="11" fill="#ede9fe"/>
  <text x="427" y="288" text-anchor="middle" font-family="system-ui,sans-serif" font-size="12" fill="#6d28d9">crates/ledge</text>

  <line x1="550" y1="211" x2="608" y2="211" stroke="#64748b" stroke-width="2" marker-end="url(#arrow)"/>

  <rect x="618" y="94" width="264" height="234" rx="14" fill="#fff7ed" stroke="#f97316" stroke-width="2"/>
  <text x="750" y="132" text-anchor="middle" font-family="system-ui,sans-serif" font-size="18" font-weight="700" fill="#c2410c">ledge-core</text>
  <text x="750" y="165" text-anchor="middle" font-family="system-ui,sans-serif" font-size="13" fill="#9a3412">Ruiz scaling</text>
  <text x="750" y="190" text-anchor="middle" font-family="system-ui,sans-serif" font-size="13" fill="#9a3412">ADMM + SMW reduced solve</text>
  <text x="750" y="215" text-anchor="middle" font-family="system-ui,sans-serif" font-size="13" fill="#9a3412">exact L1 proximal block</text>
  <text x="750" y="240" text-anchor="middle" font-family="system-ui,sans-serif" font-size="13" fill="#9a3412">audit-gated polishing</text>
  <text x="750" y="265" text-anchor="middle" font-family="system-ui,sans-serif" font-size="13" fill="#9a3412">KKT + infeasibility certificates</text>
  <rect x="667" y="286" width="166" height="25" rx="12" fill="#ffedd5"/>
  <text x="750" y="303" text-anchor="middle" font-family="system-ui,sans-serif" font-size="12" fill="#c2410c">never forms dense Σ</text>

  <text x="36" y="360" font-family="system-ui,sans-serif" font-size="13" fill="#64748b">Future private integrations stay in a separate repository and consume only these published APIs.</text>
</svg>
"""


def rolling_svg() -> str:
    dates = [(120, "t₁", "cold", "factorize"), (315, "t₂", "warm", "reuse"), (510, "t₃", "warm", "reuse"), (705, "t₂₄", "warm", "reuse")]
    cards = []
    for x, date, start, factor in dates:
        cards.append(
            f"""  <rect x="{x - 66}" y="135" width="132" height="116" rx="13" fill="#ffffff" stroke="#94a3b8"/>
  <text x="{x}" y="166" text-anchor="middle" font-family="system-ui,sans-serif" font-size="18" font-weight="700" fill="#0f172a">{date}</text>
  <text x="{x}" y="193" text-anchor="middle" font-family="ui-monospace,monospace" font-size="12" fill="#475569">update μ, w₀</text>
  <text x="{x}" y="217" text-anchor="middle" font-family="system-ui,sans-serif" font-size="12" fill="{'#b45309' if start == 'cold' else '#047857'}">{start} start</text>
  <text x="{x}" y="239" text-anchor="middle" font-family="system-ui,sans-serif" font-size="12" fill="{'#b45309' if factor == 'factorize' else '#047857'}">{factor}</text>"""
        )
    arrows = []
    for left, right in zip(dates, dates[1:]):
        arrows.append(
            f"""  <line x1="{left[0] + 67}" y1="193" x2="{right[0] - 75}" y2="193" stroke="#2563eb" stroke-width="3" marker-end="url(#arrow)"/>
  <text x="{(left[0] + right[0]) / 2}" y="178" text-anchor="middle" font-family="system-ui,sans-serif" font-size="11" fill="#1d4ed8">weights + duals</text>"""
        )
    return f"""<svg xmlns="http://www.w3.org/2000/svg" width="920" height="390" viewBox="0 0 920 390" role="img" aria-label="Rolling rebalance warm-start and factorization reuse">
  {GENERATED}
  <defs><marker id="arrow" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z" fill="#2563eb"/></marker></defs>
  <rect width="920" height="390" rx="18" fill="#f8fafc" stroke="#cbd5e1"/>
  <text x="36" y="42" font-family="Georgia,serif" font-size="24" fill="#0f172a">Rolling rebalance: update data, reuse structure</text>
  <text x="36" y="70" font-family="system-ui,sans-serif" font-size="14" fill="#475569">One PortfolioSequence keeps scaling, cached reduced factorizations, and the full primal/dual warm start.</text>
  <rect x="54" y="90" width="716" height="30" rx="15" fill="#e0e7ff"/>
  <text x="412" y="110" text-anchor="middle" font-family="ui-monospace,monospace" font-size="13" fill="#3730a3">fixed F · Ω · d · constraint matrices · bounds</text>
{chr(10).join(cards)}
{chr(10).join(arrows)}
  <rect x="790" y="109" width="95" height="165" rx="12" fill="#ecfdf5" stroke="#10b981" stroke-width="2"/>
  <text x="837.5" y="143" text-anchor="middle" font-family="system-ui,sans-serif" font-size="14" font-weight="700" fill="#047857">cache</text>
  <text x="837.5" y="173" text-anchor="middle" font-family="system-ui,sans-serif" font-size="12" fill="#065f46">scaling</text>
  <text x="837.5" y="198" text-anchor="middle" font-family="system-ui,sans-serif" font-size="12" fill="#065f46">ρ keys</text>
  <text x="837.5" y="223" text-anchor="middle" font-family="system-ui,sans-serif" font-size="12" fill="#065f46">SMW</text>
  <text x="837.5" y="248" text-anchor="middle" font-family="system-ui,sans-serif" font-size="12" fill="#065f46">KKT audit</text>
  <rect x="54" y="292" width="832" height="62" rx="12" fill="#eff6ff" stroke="#93c5fd"/>
  <text x="82" y="319" font-family="system-ui,sans-serif" font-size="14" font-weight="700" fill="#1d4ed8">Seeded 300-asset example (dates 2–24)</text>
  <text x="82" y="342" font-family="system-ui,sans-serif" font-size="13" fill="#1e3a8a">79 → 37 mean iterations · 1.71 → 0.91 ms/date · 24 → 2 reduced factorizations</text>
  <text x="886" y="377" text-anchor="end" font-family="system-ui,sans-serif" font-size="11" fill="#64748b">Source: docs/examples/rolling_backtest.py and README.md</text>
</svg>
"""


def parse_l1_rolling() -> dict[int, dict[str, float]]:
    in_table = False
    values: dict[int, dict[str, float]] = {}
    for line in REPORT.read_text(encoding="utf-8").splitlines():
        if line == "## Rolling re-solves (perturbed expected returns)":
            in_table = True
            continue
        if in_table and line.startswith("## "):
            break
        if not in_table or not line.startswith("| factor-") or "-l1 |" not in line:
            continue
        columns = [column.strip() for column in line.strip("|").split("|")]
        instance, solver = columns[0], columns[1]
        if solver not in SOLVER_COLORS:
            continue
        match = re.search(r"-n(\d+)-", instance)
        if match:
            values.setdefault(int(match.group(1)), {})[solver] = float(columns[3])
    expected = set(SOLVER_COLORS)
    if not values or any(set(row) != expected for row in values.values()):
        raise ValueError(f"incomplete L1 rolling table parsed from {REPORT}")
    return values


def comparison_svg(values: dict[int, dict[str, float]]) -> str:
    width, height = 920, 480
    left, right, top, bottom = 92, 884, 92, 382
    minimum, maximum = 0.1, 10000.0
    solvers = list(SOLVER_COLORS)
    sizes = sorted(values)

    def y(value: float) -> float:
        fraction = (math.log10(value) - math.log10(minimum)) / (
            math.log10(maximum) - math.log10(minimum)
        )
        return bottom - fraction * (bottom - top)

    grid = []
    for tick in (0.1, 1, 10, 100, 1000, 10000):
        yy = y(tick)
        label = f"{tick:g}"
        grid.append(
            f'  <line x1="{left}" y1="{yy:.1f}" x2="{right}" y2="{yy:.1f}" stroke="#e2e8f0"/>'
            f'\n  <text x="{left - 12}" y="{yy + 4:.1f}" text-anchor="end" font-family="ui-monospace,monospace" font-size="11" fill="#64748b">{label}</text>'
        )

    bars = []
    group_width = (right - left) / len(sizes)
    bar_width = 25
    for group, size in enumerate(sizes):
        center = left + group_width * (group + 0.5)
        for index, solver in enumerate(solvers):
            value = values[size][solver]
            xx = center + (index - 1) * (bar_width + 5) - bar_width / 2
            yy = y(value)
            bars.append(
                f'  <rect x="{xx:.1f}" y="{yy:.1f}" width="{bar_width}" height="{bottom - yy:.1f}" rx="3" fill="{SOLVER_COLORS[solver]}"/>'
                f'\n  <title>n={size}, {escape(solver)}: {value:g} ms/step</title>'
            )
        bars.append(
            f'  <text x="{center:.1f}" y="{bottom + 24}" text-anchor="middle" font-family="system-ui,sans-serif" font-size="12" fill="#334155">n={size}</text>'
        )

    legend = []
    for index, solver in enumerate(solvers):
        xx = 465 + index * 142
        legend.append(
            f'  <rect x="{xx}" y="50" width="13" height="13" rx="2" fill="{SOLVER_COLORS[solver]}"/>'
            f'\n  <text x="{xx + 19}" y="61" font-family="system-ui,sans-serif" font-size="12" fill="#334155">{escape(solver)}</text>'
        )
    return f"""<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}" role="img" aria-label="L1 rolling median solve time comparison">
  {GENERATED}
  <rect width="{width}" height="{height}" rx="18" fill="#f8fafc" stroke="#cbd5e1"/>
  <text x="36" y="38" font-family="Georgia,serif" font-size="23" fill="#0f172a">L1 rolling re-solves: published median time</text>
  <text x="36" y="62" font-family="system-ui,sans-serif" font-size="13" fill="#475569">10 bps proportional costs · external solvers use lifted epigraphs · log scale (ms/step)</text>
{chr(10).join(legend)}
{chr(10).join(grid)}
  <line x1="{left}" y1="{bottom}" x2="{right}" y2="{bottom}" stroke="#94a3b8" stroke-width="1.5"/>
{chr(10).join(bars)}
  <text x="36" y="454" font-family="system-ui,sans-serif" font-size="12" fill="#475569">Every bar comes from benchmarks/results/2026-07-l1/summary.md (10 repeats × 10 rolling steps; read the report before quoting).</text>
</svg>
"""


def capture_terminal() -> None:
    data = json.loads(TERMINAL_DATA.read_text(encoding="utf-8"))
    completed = subprocess.run(
        shlex.split(data["command"]),
        cwd=ROOT,
        check=True,
        text=True,
        capture_output=True,
    )
    output = [line for line in completed.stdout.strip().splitlines() if line]
    if len(output) < 3 or "Solved" not in output[-1]:
        raise RuntimeError(f"unexpected synthetic example output:\n{completed.stdout}")
    data["output"] = output
    TERMINAL_DATA.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def terminal_gif() -> bytes | None:
    try:
        from PIL import Image, ImageDraw, ImageFont
    except ImportError:
        return None

    data = json.loads(TERMINAL_DATA.read_text(encoding="utf-8"))
    command = data["command"]
    row = [column.strip() for column in data["output"][-1].strip("|").split("|")]
    if len(row) != 8:
        raise ValueError(f"unexpected terminal table row: {data['output'][-1]}")
    instance, _solver, status, objective, primal, dual, iterations, elapsed = row
    width, height = 920, 430
    font_path = Path("/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf")
    bold_path = Path("/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf")
    if font_path.exists():
        font = ImageFont.truetype(str(font_path), 16)
        small = ImageFont.truetype(str(font_path), 13)
        bold = ImageFont.truetype(str(bold_path if bold_path.exists() else font_path), 16)
    else:
        font = small = bold = ImageFont.load_default()

    displayed = [
        "$ " + command,
        "",
        "instance                 status   objective       primal     dual        iters  time",
        f"{instance:<24} {status:<8} {objective:<15} {primal:<10} {dual:<10}  {iterations:<5}  {elapsed} ms",
        "",
        "✓ independently audited residuals · release build · seeded input",
    ]
    frames = []
    stages = [
        ("", 550),
        ("$ " + command[:35], 500),
        ("$ " + command, 750),
        ("\n".join(displayed[:3]), 700),
        ("\n".join(displayed[:4]), 1000),
        ("\n".join(displayed), 3600),
    ]
    for content, duration in stages:
        image = Image.new("RGB", (width, height), "#0b1220")
        draw = ImageDraw.Draw(image)
        draw.rounded_rectangle((1, 1, width - 2, height - 2), radius=16, outline="#334155", width=2)
        draw.rounded_rectangle((2, 2, width - 3, 49), radius=15, fill="#172033")
        draw.rectangle((2, 31, width - 3, 49), fill="#172033")
        for x, color in ((24, "#fb7185"), (48, "#fbbf24"), (72, "#4ade80")):
            draw.ellipse((x - 7, 18, x + 7, 32), fill=color)
        draw.text((width // 2, 24), "Ledge · reproducible synthetic solve", anchor="mm", font=bold, fill="#e2e8f0")
        y_pos = 78
        for line in content.splitlines():
            color = "#60a5fa" if line.startswith("$") else "#e2e8f0"
            if line.startswith("✓"):
                color = "#4ade80"
            draw.text((28, y_pos), line, font=small if len(line) > 92 else font, fill=color)
            y_pos += 43 if line == "" else 35
        draw.text(
            (28, height - 28),
            f"captured {data['captured_at']} · timing is machine-dependent, not a benchmark",
            font=small,
            fill="#94a3b8",
        )
        image.info["duration"] = duration
        frames.append(image)

    output = io.BytesIO()
    frames[0].save(
        output,
        format="GIF",
        save_all=True,
        append_images=frames[1:],
        duration=[frame.info["duration"] for frame in frames],
        loop=0,
        disposal=2,
        optimize=False,
    )
    return output.getvalue()


def write(path: Path, content: str | bytes, check: bool) -> bool:
    encoded = content.encode("utf-8") if isinstance(content, str) else content
    if check:
        return path.exists() and path.read_bytes() == encoded
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists() or path.read_bytes() != encoded:
        path.write_bytes(encoded)
        print(f"wrote {path.relative_to(ROOT)}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--capture-terminal",
        action="store_true",
        help="run the seeded Rust example and refresh terminal-demo.json",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if generated assets differ (GIF checked only when Pillow is installed)",
    )
    args = parser.parse_args()
    if args.capture_terminal and args.check:
        parser.error("--capture-terminal and --check cannot be combined")
    if args.capture_terminal:
        capture_terminal()

    architecture = architecture_svg()
    rolling = rolling_svg()
    comparison = comparison_svg(parse_l1_rolling())
    outputs: dict[Path, str | bytes] = {
        ASSETS / "architecture.svg": architecture,
        ASSETS / "rolling-rebalance.svg": rolling,
        ASSETS / "l1-rolling-comparison.svg": comparison,
        BOOK_ASSETS / "architecture.svg": architecture,
        BOOK_ASSETS / "rolling-rebalance.svg": rolling,
        BOOK_ASSETS / "l1-rolling-comparison.svg": comparison,
    }
    gif = terminal_gif()
    if gif is not None:
        outputs[ASSETS / "terminal-demo.gif"] = gif
    elif args.capture_terminal:
        raise RuntimeError("Pillow is required to render terminal-demo.gif")

    stale = [path for path, content in outputs.items() if not write(path, content, args.check)]
    if stale:
        for path in stale:
            print(f"stale: {path.relative_to(ROOT)}", file=sys.stderr)
        return 1
    if args.check:
        print(f"{len(outputs)} generated assets are current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
